"""API registry JSON export contract.

P2.1: ``data/api_registry.json`` is the intermediate file that P2.2 will load
as an alternative source. This file is generated by ``tools/export_api_registry.py``
from the in-memory ``ALL_ENDPOINTS`` tuple.

Two invariants pinned here:

  1. **Round-trip is lossless.** Every dataclass field — including the optional
     semantic-enrichment ones (``field_schema`` / ``use_cases`` / ``chain_with`` /
     ``analysis_note`` / ``method``) — survives serialize→deserialize unchanged.
  2. **Checked-in JSON is fresh.** If someone edits ``api_registry.py`` and
     forgets to re-run the exporter, CI fails here, surfacing the divergence
     before P2.2 starts trusting the file.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from backend.agent.api_registry import (
    _CODE_DOMAIN_INDEX,
    _CODE_ENDPOINTS,
    load_from_json,
    serialize_to_dict,
)
from tools.export_api_registry import DEFAULT_OUTPUT

pytestmark = pytest.mark.contract


def test_serialize_deserialize_round_trip_is_lossless():
    payload = serialize_to_dict()
    domains, endpoints = load_from_json(payload)
    assert endpoints == _CODE_ENDPOINTS
    assert domains == _CODE_DOMAIN_INDEX


def test_endpoint_count_matches():
    payload = serialize_to_dict()
    assert len(payload["endpoints"]) == len(_CODE_ENDPOINTS)
    assert len(payload["domains"]) == len(_CODE_DOMAIN_INDEX)


def test_checked_in_json_matches_current_registry():
    """If this fails, run ``python -m tools.export_api_registry`` and commit
    the regenerated ``data/api_registry.json``."""
    assert DEFAULT_OUTPUT.exists(), (
        f"{DEFAULT_OUTPUT} missing — run `python -m tools.export_api_registry`"
    )
    with open(DEFAULT_OUTPUT, encoding="utf-8") as f:
        on_disk = json.load(f)
    assert on_disk == serialize_to_dict(), (
        f"{DEFAULT_OUTPUT} is stale — run `python -m tools.export_api_registry`"
    )
